export const CLIENT_ID = 'ownerapi';
export const REDIRECT_URI = 'https://auth.tesla.com/void/callback';
export const AUTH_URL = 'https://auth.tesla.com/oauth2/v3/authorize';
export const TOKEN_URL = 'https://auth.tesla.com/oauth2/v3/token';
export const SCOPE = 'openid email offline_access';
export const CODE_CHALLENGE_METHOD = 'S256';
export const APP_VERSION = '9.99.9-9999';
export const ORDERS_API_URL = 'https://owner-api.teslamotors.com/api/1/users/orders';
export const ORDER_DETAILS_API_URL_TEMPLATE = 'https://akamai-apigateway-vfx.tesla.com/tasks?deviceLanguage=en&deviceCountry=US&referenceNumber={ORDER_ID}&appVersion=' + APP_VERSION;
export const PROXY_API_URL = 'https://tesla-delivery-277250840124.europe-west1.run.app/';
export const GITHUB_REPO_URL = 'https://github.com/VDenisyuk/tesla-delivery-status-web';